Repository LevShlyogin/Balance_plus, pull requests merged in 2025-09, with the labels that each got.

#127 Metrovickers strategy
  tests/report_metrovickers_strategy.py
  tests/test_custom_interpolates.py
  tests/test_metrovickers_strategy.py
  utils/Constants.py
  utils/custom_interpolates.py
  utils/metrovickers_strategy.py
Labels: enhancement, development

#146 Develop
  .gitignore
  .idea/.gitignore
  .idea/vcs.xml
  requirements.txt
  tests/compare_selection_methods.py
  tests/generate_report_on_selecting_values.py
  tests/report_TPS_module.py
  tests/report_metrovickers_strategy.py
  tests/report_module_berman.py
  tests/test_VKU_strategy.py
  tests/test_custom_interpolates.py
  tests/test_division_range.py
  tests/test_metrovickers_strategy.py
  tests/test_module_berman.py
  tests/test_selecting_values.py
  tests/test_table_models.py
  tests/test_uniconv.py
  tests/validate_TPS_module.py
  tests/validate_exceptions_method.py
  tests/validate_vku.py
  utils/Constants.py
  utils/TPS_module.py
  utils/VKU_strategy.py
  utils/base_for_selection.py
  utils/berman_strategy.py
  utils/custom_interpolates.py
  utils/division_range.py
  utils/exceptions_method.py
  utils/metrovickers_strategy.py
  utils/selection_methods.py
  utils/table_models.py
  utils/uniconv.py
Labels: good first issue, development

#176 doc: обновлена документация проекта
  Materials/ред2_Преза_для_завода_триквел.pptx
  README.md
  docs/README.md
  docs/architecture/C2_Containers.md
  docs/architecture/platform/container-orchestration.md
  docs/architecture/platform/data-schema-management.md
  docs/architecture/platform/gitlab.md
  docs/architecture/platform/message-broker.md
  docs/architecture/platform/observability.md
  docs/architecture/platform/postgresql-database.md
  docs/architecture/services/api-gateway.md
  docs/architecture/services/frontend-ide.md
  docs/architecture/services/orchestrator.md
  docs/materials/1.txt
  docs/materials/25.04.21_Балансы.pdf
  docs/materials/25.04.25_Пользовательское ТЗ.docx
  docs/materials/Общая схема.pdf
  docs/materials/ред2_Преза_для_завода_триквел.pptx
  docs/materials/ред4_Для презентации.docx
  docs/materials/ред_План разработки БАЛАНС+ (для руководства).xlsx
  tests/__init__.py
  tests/test_custom_interpolates.py
  utils/__init__.py
  utils/custom_interpolates.py
Labels: documentation, analysis
